### ISSUE TITLE
PEER TO PEER CODE REVIEW.

### ISSUE THREAD

**Issue by AdnanOlarmmi** [adel-gu/awesome-books#2]
# Required Changes 🔁
# Hi @adel-gu and @TechnoAndy 

This is @adnanolarmmi, your colleague.

Good job so far 👏 👏
Your Project is almost on point. There are a few changes you could effect to make it superb 😃.

![Almost there pilot](https://user-images.githubusercontent.com/41163571/191337038-d1822aaf-43e7-4414-9dbe-ca009fd43b31.gif)

## Highlights
✔️ All linters passing
✔️ Correct Gitflow
✔️Descriptive commit messages 

## Required Changes♻️ 
- [x] Please, I advise that the [Built with](https://github.com/adel-gu/awesome-books/blob/master/README.md#built-with) section in your [README](https://github.com/adel-gu/awesome-books/blob/master/README.md) file should include other languages used e.g. CSS. 🙂

- [x] I suggest that you do away with options you aren't using in your [README](https://github.com/adel-gu/awesome-books/blob/master/README.md) like the [Live Demo](https://github.com/adel-gu/awesome-books/blob/master/README.md#live-demo-if-available), It should only be there _if available_. 😃 

- [x] I also suggest likewise that you have a detailed description of how your code can be cloned and used in the [Getting started](https://github.com/adel-gu/awesome-books/blob/master/README.md#getting-started) section under your [README](https://github.com/adel-gu/awesome-books/blob/master/README.md) file as well, You can use [this template](https://github.com/microverseinc/readme-template) 😀 

## Optional suggestions:

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@AdnanOlarmmi ] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------------

**Comment by adel-gu** [comment]
Hi @AdnanOlarmmi 👋, 

Thank you for the review, All issues have been resolved, feel free to recheck this repo.
Cheers and Happy coding!👏👏👏.

**Comment by AdnanOlarmmi** [comment]
# Project Approved 🙂👍 

# Hi @adel-gu and @TechnoAndy 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉 

# Highlights:
- All requirements completed
- Professional readme

![DiCaprion cheers](https://user-images.githubusercontent.com/41163571/193562274-01e3c926-ee0f-432e-b55a-747f1f0e521f.gif)

## Optional suggestions:

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@AdnanOlarmmi ] in your question so I can receive the notification.

------
